import { FileSystemMap, BuildStep, ChatMessage } from "./types";

export const initialFiles: FileSystemMap = {
  "oxide-plugin-intellij": {
    name: "oxide-plugin-intellij",
    path: "oxide-plugin-intellij",
    icon: "folder",
    isFolder: true,
    children: [
      "front",
      "reference",
      "rust",
      "src",
      "target",
      ".gitignore",
      "Cargo.lock",
      "Cargo.toml",
      "Dioxus.toml",
    ],
    content: "",
  },
  "front": {
    name: "front",
    path: "front",
    icon: "folder",
    isFolder: true,
    children: ["front/package.json", "front/src"],
    content: "",
  },
  "front/package.json": {
    name: "package.json",
    path: "front/package.json",
    icon: "description",
    content: `{
  "name": "front",
  "version": "0.1.0",
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}`,
  },
  "front/src": {
    name: "src",
    path: "front/src",
    icon: "folder",
    isFolder: true,
    children: ["front/src/App.tsx"],
    content: "",
  },
  "front/src/App.tsx": {
    name: "App.tsx",
    path: "front/src/App.tsx",
    icon: "code",
    content: `export default function App() {
  return <div>Front App</div>;
}`,
  },
  "reference": {
    name: "reference",
    path: "reference",
    icon: "folder",
    isFolder: true,
    children: ["reference/App.tsx", "reference/index.css"],
    content: "",
  },
  "reference/App.tsx": {
    name: "App.tsx",
    path: "reference/App.tsx",
    icon: "code",
    content: `// React code to be refactored to rust
export interface AutomationSkill {
  id: string;
  name: string;
  description: string;
  script: string;
  type: string;
  trigger: string;
}
`,
  },
  "reference/index.css": {
    name: "index.css",
    path: "reference/index.css",
    icon: "description",
    content: `body {
  margin: 0;
  background-color: #000;
}`,
  },
  "rust": {
    name: "rust",
    path: "rust",
    icon: "folder",
    isFolder: true,
    children: ["rust/Cargo.toml"],
    content: "",
  },
  "rust/Cargo.toml": {
    name: "Cargo.toml",
    path: "rust/Cargo.toml",
    icon: "description",
    content: `# Pre-configured Cargo file for Rust subproject
[package]
name = "duoxus-bridge"
version = "0.1.0"
edition = "2021"
`,
  },
  "src": {
    name: "src",
    path: "src",
    icon: "folder",
    isFolder: true,
    children: ["src/models.rs", "src/main.rs"],
    content: "",
  },
  "src/models.rs": {
    name: "models.rs",
    path: "src/models.rs",
    icon: "data_object",
    content: `use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct AutomationSkill {
    pub id: String,
    pub name: String,
    pub description: String,
    pub script: String,
    #[serde(rename = "type")]
    pub type_: String,
    pub trigger: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_executed: Option<String>,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub execution_log: Option<String>,
}

#[derive(Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct McpExtension {
    pub id: String,
    pub name: String,
    pub description: String,
}
`,
  },
  "src/main.rs": {
    name: "main.rs",
    path: "src/main.rs",
    icon: "data_object",
    content: `use dioxus::prelude::*;
mod models;

fn main() {
    dioxus_desktop::launch(app);
}

fn app(cx: Scope) -> Element {
    cx.render(rsx! {
        div {
            class: "flex flex-col items-center justify-center h-screen bg-slate-900 text-white",
            h1 { "NexusIDE Plugin Activated" }
            p { "Ready for high-velocity rust development." }
        }
    })
}
`,
  },
  "target": {
    name: "target",
    path: "target",
    icon: "folder",
    isFolder: true,
    children: ["target/debug"],
    content: "",
  },
  "target/debug": {
    name: "debug",
    path: "target/debug",
    icon: "folder",
    isFolder: true,
    children: [],
    content: "",
  },
  ".gitignore": {
    name: ".gitignore",
    path: ".gitignore",
    icon: "description",
    content: `/target
**/*.rs.bk
Cargo.lock
`,
  },
  "Cargo.lock": {
    name: "Cargo.lock",
    path: "Cargo.lock",
    icon: "lock",
    content: `# This file is automatically generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "oxide-plugin-intellij"
version = "0.1.0"
`,
  },
  "Cargo.toml": {
    name: "Cargo.toml",
    path: "Cargo.toml",
    icon: "description",
    content: `[workspace]
members = [
    "rust",
    "uniffi-bridge"
]

[package]
name = "oxide-plugin-intellij"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.4", features = ["desktop"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
`,
  },
  "Dioxus.toml": {
    name: "Dioxus.toml",
    path: "Dioxus.toml",
    icon: "description",
    content: `# Dioxus application configuration
[application]
name = "oxide-plugin-intellij"
asset_dir = "assets"
`,
  },
};

export const initialBuildSteps: BuildStep[] = [
  {
    id: "cargo-failed",
    name: "Cargo:",
    status: "error",
    time: "At 22/06/2026, 19:35 with 1 error",
    duration: "547 ms",
    children: [
      {
        id: "sync-project",
        name: "Sync oxide-plugin-intellij project",
        status: "error",
        time: "1 error",
        duration: "304 ms",
        children: [
          {
            id: "update-workspace",
            name: "Updating workspace info",
            status: "error",
            time: "1 error",
            duration: "45 ms",
            children: [
              {
                id: "failed-run-cargo",
                name: "Failed to run Cargo",
                status: "error",
              },
            ],
          },
        ],
      },
    ],
  },
];

export const initialChats: ChatMessage[] = [
  {
    id: "chat-1",
    role: "user",
    text: "refactor all the react typescript code in reference/ dir to rust/duoxus code",
  },
  {
    id: "chat-2",
    role: "model",
    text: "Okay, I will start by listing the files in the `reference/` directory to understand the scope of the refactoring.",
    toolLogs: [
      {
        action: "Listed files in /home/jrad/RustroverProjects/Oxide-tech-plugins-workspace/oxide-plugin-intellij/reference/",
        status: "success",
        detail: "App.tsx, index.css",
      },
    ],
  },
  {
    id: "chat-3",
    role: "model",
    text: "Okay, `reference/` is a TypeScript project. Now, I'll check the `rust/` directory to understand its structure.",
    toolLogs: [
      {
        action: "Failed listing files in /home/jrad/RustroverProjects/Oxide-tech-plugins-workspace/oxide-plugin-intellij/rust/...",
        status: "error",
        detail: "No such directory",
      },
    ],
  },
  {
    id: "chat-4",
    role: "model",
    text: "Okay, the `rust/` directory doesn't exist. I'll create a new Rust project in that directory. I'll start by creating the `Cargo.toml` file.",
    toolLogs: [
      {
        action: "Edited rust/Cargo.toml",
        status: "success",
        detail: "+6 lines generated",
      },
    ],
  },
];
